# --------------------------------------------
# Server Configuration
# --------------------------------------------
server:
  port: 8080
  servlet:
    context-path: /

# --------------------------------------------
# Log Configuration
# --------------------------------------------
logging:
  level:
    root: INFO